CREATE TABLE [dbo].[constants]
(
	[CAGE_SIZE] INT NOT NULL DEFAULT 9, 
    [TOTAL_CELL_COUNT] INT NOT NULL DEFAULT 81, 
    [CANDIDATE_DIGIT_SET] BIT NOT NULL DEFAULT 1, 
    [CANDIDATE_DIGIT_NOTSET] BIT NOT NULL DEFAULT 0, 
    [DIGIT_OUTPUT_NOTKNOWN] INT NOT NULL DEFAULT 0, 
    [CANDIDATES_NA] INT NOT NULL DEFAULT 0, 
    [FIRST_CELL_ID] INT NOT NULL DEFAULT 1, 
    [FIRST_DIGIT_ID] INT NOT NULL DEFAULT 1
)
